# Generated by Django 4.2 on 2023-04-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrStatus', models.CharField(max_length=10)),
                ('hr', models.FloatField()),
                ('ibi', models.FloatField()),
                ('qIbi', models.FloatField()),
            ],
        ),
    ]
