# Generated by Django 4.2 on 2023-04-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='hr_status',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='q_ibi',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='hrv',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
