# Generated by Django 4.2 on 2023-04-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sensordata_hr_status_remove_sensordata_q_ibi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
