# Generated by Django 4.2 on 2023-06-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='reference',
            field=models.FloatField(default=0),
        ),
    ]
