# Generated by Django 4.2 on 2025-01-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_session_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
