# Generated by Django 4.2 on 2025-01-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sensordata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='status',
            field=models.IntegerField(default=404),
        ),
    ]
