# Generated by Django 4.2 on 2025-02-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_ppggreendata_ppg_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='hrvWithInvalid',
            field=models.FloatField(default=0.0),
        ),
    ]
