# Generated by Django 4.2 on 2025-03-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_sensordata_hrvwithinvalid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='ibiStatus',
            new_name='ibiStatus0',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='ibi',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='ibi0',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='ibi1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='ibi2',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='ibi3',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='ibiOld',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='ibiStatus1',
            field=models.IntegerField(default=404),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='ibiStatus2',
            field=models.IntegerField(default=404),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='ibiStatus3',
            field=models.IntegerField(default=404),
        ),
    ]
