# Generated by Django 4.2 on 2025-03-02 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_ppgirdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinTemperatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectTemperature', models.FloatField()),
                ('ambientTemperature', models.FloatField()),
                ('status', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.session')),
            ],
        ),
    ]
